### ISSUE TITLE
For unrecognised command, syntax is not correctly explained

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#84] opened 2022-07-01 14:29 UTC
Example : 
```Powershell
MyFunction myParem
```

![image](https://user-images.githubusercontent.com/4894452/176912830-67461aef-4ac8-4020-9ac0-e28b8f08dbd7.png)

Inside a console :
![image](https://user-images.githubusercontent.com/4894452/176913181-d281c1cc-020d-4008-a25e-f91f20b0e960.png)

The AST :
![image](https://user-images.githubusercontent.com/4894452/176912588-f97a9c4e-0d5b-4c04-8684-8c6d3d65c75c.png)

**Comment by Jawz84** [comment] 2022-07-01 19:22
Duplicate of #32, closing that one in favour of this one. 

A solution could be to mark unrecognized commands as such:

```text
MyFonction myparam
MyFonction (unrecognized command)
```

**Closed** 2022-07-04 20:45 UTC
